#!/bin/bash
# Demo script showing the new -l flag functionality
# This is for demonstration purposes only

echo "==================================="
echo "SSH-X-Term Quick Connect Demo"
echo "==================================="
echo ""

echo "0. First time initialization:"
echo "   $ sxt -i"
echo "   → Initializes SSH-X-Term"
echo "   → Migrates old JSON config (if exists)"
echo "   → Creates backup of SSH config"
echo "   → Required before using -l flag"
echo ""

echo "1. Standard mode (Full TUI):"
echo "   $ sxt"
echo "   → Launches full Bubble Tea interface"
echo "   → Requires tmux"
echo "   → Full connection management"
echo ""

echo "2. Quick connect mode (NEW!):"
echo "   $ sxt -l"
echo "   → Shows minimal connection list"
echo "   → Start typing immediately - filter activates automatically!"
echo "   → Arrow keys exit filter mode and navigate"
echo "   → 10 connections per page"
echo "   → Press Enter to connect"
echo "   → Press Esc to clear filter or quit"
echo "   → No tmux required"
echo ""

echo "3. Help:"
echo "   $ sxt -h"
./sxt -h
echo ""

echo "==================================="
echo "Example workflow:"
echo "==================================="
echo ""
echo "# First time setup"
echo "$ sxt -i"
echo "  → Initializes configuration"
echo "  → Migrates any old settings"
echo ""
echo "# Add connections (one time setup)"
echo "$ sxt"
echo "  → Add your servers with 'a' key"
echo "  → Save passwords to keyring"
echo "  → Exit with Ctrl+C"
echo ""
echo "# Daily use (fast!)"
echo "$ sxt -l"
echo "  → Immediately type 'prod' to filter production servers"
echo "  → Arrow down/up to select"
echo "  → Press Enter on desired server"
echo "  → Instant connection!"
echo ""

echo "==================================="
echo "Shell alias recommendation:"
echo "==================================="
echo ""
echo "Add to your ~/.bashrc or ~/.zshrc:"
echo ""
echo "  alias sshq='sxt -l'"
echo ""
echo "Then just use:"
echo "  $ sshq"
echo ""

echo "==================================="
echo "Authentication methods supported:"
echo "==================================="
echo ""
echo "✓ SSH Agent (most secure)"
echo "✓ Private Key Files (~/.ssh/id_rsa, etc.)"
echo "✓ Password (stored in system keyring)"
echo ""
echo "On Unix/Linux/macOS:"
echo "  - Key auth: native ssh command"
echo "  - Password: passh wrapper (auto password entry)"
echo ""
echo "On Windows:"
echo "  - Key auth: native ssh command"
echo "  - Password: plink.exe (PuTTY's SSH client)"
echo ""
